name: Build and deploy Node.js app to Azure Web App - opeania-realtime-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm clean install and build
        run: |
          cd web
          npm install
          npm run build:debug

      - name: Zip artifact for deployment
        run: |
          cd web
          zip release.zip ./* .next -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: web/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_833C600475504E9A9DE2883F5F7373D8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F86299335F7847A6BAD3A4D0234AFD83 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_90CF116DC12846AEB8C9B36FA3A6CB0B }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'opeania-realtime-api'
          slot-name: 'Production'
          package: ./web